const featuredProperties = [
  {
    id: 21723,
    name: 'Sofi Stadium',
    street: '20 VAN DAM ST',
    city: 'BROOKLYN',
    state: 'NY',
    zipCode: 11222,
    favorite: false,
    propertyType: 'Industrial',
    saleType: 'Auction',
    auctionDates: 'Oct 31 - Nov 2, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 1800000,
    img: [
      'https://upload.wikimedia.org/wikipedia/commons/0/0b/SoFi_Stadium_2021.jpg',
    ],
  },

  {
    id: 21724,
    name: 'Great Western Forum',
    street: '123 MAIN ST',
    city: 'INGLEWOOD',
    state: 'CA',
    zipCode: 90023,
    favorite: false,
    propertyType: 'Land',
    saleType: 'Auction',
    auctionDates: 'Nov 2 - Nov 4, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 7800000,
    img: [
      'https://img.bleacherreport.net/img/images/photos/003/796/470/hi-res-dbcd777fd246dd88d56827501b904f14_crop_north.jpg?1552593600&w=3072&h=2048',
    ],
  },

  {
    id: 21725,
    name: 'Staples Center',
    street: '604 W NORTH AVE.',
    city: 'PITTSBURGH',
    state: 'PA',
    zipCode: 15212,
    favorite: false,
    propertyType: 'Flex',
    saleType: 'Auction',
    auctionDates: 'Nov 4 - Nov 6, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 1900000,
    img: [
      'https://s.yimg.com/ny/api/res/1.2/dvcEr5j3e5CxLo8UOZyQYQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/os/creatr-uploaded-images/2021-11/4a157f60-4763-11ec-b77f-706841756ccd',
    ],
  },

  {
    id: 21726,
    name: 'Madison Square Garden',
    street: '287 SE RACE TRACK LN',
    city: 'LAKE CITY',
    state: 'FL',
    zipCode: 32025,
    favorite: false,
    propertyType: 'Hotel',
    saleType: 'Auction',
    auctionDates: 'Nov 6 - Nov 8, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 23000000,
    img: [
      'https://image.newyork.co.uk/wp-content/uploads/2015/03/Madison-Square-Garden-in-New-York.jpg',
    ],
  },
  {
    id: 21727,
    name: 'T-Mobile Arena',
    street: '287 SE RACE TRACK LN',
    city: 'LAKE CITY',
    state: 'FL',
    zipCode: 32025,
    favorite: false,
    propertyType: 'Hotel',
    saleType: 'Auction',
    auctionDates: 'Nov 6 - Nov 8, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 23000000,
    img: [
      'https://www.sportstravelmagazine.com/wp-content/uploads/2016/01/TMobileArenaImage.jpg',
    ],
  },
  {
    id: 21728,
    name: 'Allegiant Stadium',
    street: '287 SE RACE TRACK LN',
    city: 'LAKE CITY',
    state: 'FL',
    zipCode: 32025,
    favorite: false,
    propertyType: 'Hotel',
    saleType: 'Auction',
    auctionDates: 'Nov 6 - Nov 8, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 23000000,
    img: [
      'https://upload.wikimedia.org/wikipedia/commons/2/23/Allegiant_Stadium_%28cropped%29.jpg',
    ],
  },
  {
    id: 21729,
    name: 'Century Link Field',
    street: '287 SE RACE TRACK LN',
    city: 'SEATTLE',
    state: 'WA',
    zipCode: 32025,
    favorite: false,
    propertyType: 'Hotel',
    saleType: 'Auction',
    auctionDates: 'Nov 6 - Nov 8, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 23000000,
    img: [
      'https://cdn.vox-cdn.com/thumbor/LrdtSQhsiEPnme6Kw9ChayRUPrc=/0x0:4000x2667/1200x675/filters:focal(2050x1355:2690x1995)/cdn.vox-cdn.com/uploads/chorus_image/image/60779781/CenturyLink.6.jpg',
    ],
  },
  {
    id: 21730,
    name: 'Mile High Stadium',
    street: '287 SE RACE TRACK LN',
    city: 'DENVER',
    state: 'CO',
    zipCode: 32025,
    favorite: false,
    propertyType: 'Hotel',
    saleType: 'Auction',
    auctionDates: 'Nov 6 - Nov 8, 2022',
    banners: ['Broker Co-Op', 'Financing Available'],
    startingBid: 23000000,
    img: [
      'https://wp-cpr.s3.amazonaws.com/uploads/2022/12/220126-EMPOWER-FIELD-AT-MILE-HIGH-STADIUM-SUN-VALLEY-SPORTS-DRONE-KEVINJBEATY-01.jpg',
    ],
  },
];
export { featuredProperties as featuredPropertiesModel };
